### PR TITLE
WIP: feat: naive system tray widget

### PR DESCRIPTION
**Pull request by oknozor**
This is still a work in progress, properties needs to be added at least to configure the icon size, gtk menu and menuitem scss classes for the system tray. 

While this is functional this needs to be tested against various applications. 

## Description

Add a system tray widget

## Usage

For now there is just a `(system-tray)` widget with no prop binding. 

### Showcase

see #111

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [ ] All widgets I've added are correctly documented.
- [ ] I added my changes to CHANGELOG.md, if appropriate.
- [ ] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

### CODE REVIEW

**Comment by elkowar** [comment]
I've had a first look through the code right now, and this looks very promising!
Not a fan of the amount of `.unwrap` / `.expect` calls currently, but I assume that's gonna be relatively easy to sort out and do cleanly.
Having global state for this is generally fine - as i'm assuming that's pretty much unavoidable.
I think the functions etc in system_tray could definitely use some more comments and a bit more structure -- currently, spawn_local_handler does a lot more than just _spawn_ some handler ^^

I haven't looked into the all the exact details yet, but the approach taken here definitely looks good!
Good job already!

**Comment by oknozor** [comment]
Actually there is one big problem here. Every time a menu gets updated it closes and reopen. 

For instance when using `nm-applet --indicator` if an update occurs (a new wifi network is seen on the interface) while I open the applet, the menu closes and I need to reopen it to see the update. 

I have talked with the gtk-rs folks and it seems the solution is to implement a custom MenuModel.
This seems doable but it involves a lot more boiler plate, and unsafe ffi function usage(an example for `gio::ListModel` https://github.com/gtk-rs/gtk-rs-core/blob/master/gio/src/subclass/list_model.rs.  

So I will probably break everything again soon. 

Now I am wondering if it would be better to expose the custom MenuModel  from my crate or keep the gtk stuff in eww. 

I'll keep you updated :)

**Comment by elkowar** [comment]
I'd think if you wanted to put some GTK stuff into your crate, it might be worth it to actually make a second crate (`gtk-stray` or sth), to keep the core system tray handling separate from specific frontend stuff -- that'd allow other projects to also make use of your stray implementation without necessarily needing to use the gtk frontend. 
Generally tho, if this _does_ become complex enough, I could see putting the gtk-stuff into a separate crate rather than into eww be worthwhile 👍🏻

**Comment by oknozor** [comment]
Hey @elkowar I've tried to implement a custom MenuModel without success. I don't think I will be able to do it without help. 
That said the current, naive implementation work as is :
screenshot-2022-06-15T11:16:51

Let me know what you want to do.

**Comment by MonAaraj** [comment]
Awesome work! I'm looking forward for this to be merged to master. I think I might be able to help. Is there any place to converse about this? any EWW room or such?

**Comment by TornaxO7** [comment]
May I ask what the current state is of this PR?

**Comment by dnordstrom** [comment]
For what it's worth, I'm trying this out on NixOS on River (Wayland) and I get the following error about icon info lookup:

```
thread 'main' panicked at 'Failed to lookup icon info', crates/eww/src/widgets/system_tray.rs:76:88
stack backtrace:
   0:     0x5580aa0ff2dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90d86d5e49dcdb23
   1:     0x5580aa138c8e - core::fmt::write::hf402a79d5884ad76
   2:     0x5580aa104fd1 - std::io::Write::write_fmt::h1839547170afd413
   3:     0x5580aa1120a5 - std::panicking::default_hook::{{closure}}::h1d6d5b9a19e531e9
   4:     0x5580aa111d2a - std::panicking::default_hook::h78a6ac0c850df841
   5:     0x5580aa11258c - std::panicking::rust_panic_with_hook::ha3460b9892f156c0
   6:     0x5580aa100007 - std::panicking::begin_panic_handler::{{closure}}::h89605b23b2447736
   7:     0x5580aa0ff6b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h20c2a9b05a320fe6
   8:     0x5580aa112252 - rust_begin_unwind
   9:     0x5580a98dd4b3 - core::panicking::panic_fmt::hab911959b97bc6d9
  10:     0x5580aa13ed81 - core::panicking::panic_display::he8b09729440fceed
  11:     0x5580aa13ed2b - core::panicking::panic_str::h4e2544976daaf571
  12:     0x5580a98dd676 - core::option::expect_failed::h7c61aacccb08ad84
  13:     0x5580a9a37f85 - eww::widgets::system_tray::NotifierItem::get_icon::h44c3fc2ad0506b71
  14:     0x5580a99b1190 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4f6e11f34a6f16ef
  15:     0x5580aa0e328c - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::hccad9d8f02533033
  16:     0x5580aa0decaa - glib::main_context_futures::TaskSource::dispatch::h575e8baf5d618d63
  17:     0x7f5001e8ddfb - g_main_context_dispatch
  18:     0x7f5001e8e0a8 - g_main_context_iterate.constprop.0
  19:     0x7f5001e8e393 - g_main_loop_run
  20:     0x7f50025fa375 - gtk_main
  21:     0x5580a9aba579 - eww::server::initialize_server::h172ed4c880e186da
  22:     0x5580a9a39302 - eww::main::h4d89aa5698bad2de
  23:     0x5580a99fa923 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfcca3777e9002403
  24:     0x5580a99ce469 - std::rt::lang_start::{{closure}}::hb1e9e012b522d946
  25:     0x5580aa104951 - std::rt::lang_start_internal::he9577dbc8903283e
  26:     0x5580a9a3c512 - main
  27:     0x7f5001b89237 - __libc_start_call_main
  28:     0x7f5001b892f5 - __libc_start_main_impl
  29:     0x5580a98dd6a1 - _start
  30:                0x0 - <unknown>
```

**Comment by dnordstrom** [comment]
Some more info:

Doesn't matter which icon theme I use. I've tried setting a few different ones with dconf Editor (there are no schemas installed in "gsettings", but dconf Editor does the trick) as well as by editing the settings.ini for GTK 3 and 4, including setting it back to the default.

I suppose it shouldn't panic if it can't find an icon anyway, but the tray works fine in Sway with Waybar so that's a bit strange. Waybar causes River to panic and exit for me though, even if I just have a clock enabled. :stuck_out_tongue:

**Comment by yavko** [comment]
> Some more info:
> 
> Doesn't matter which icon theme I use. I've tried setting a few different ones with dconf Editor (there are no schemas installed in "gsettings", but dconf Editor does the trick) as well as by editing the settings.ini for GTK 3 and 4, including setting it back to the default.
> 
> I suppose it shouldn't panic if it can't find an icon anyway, but the tray works fine in Sway with Waybar so that's a bit strange. Waybar ~causes River to panic and exit for me though, even if I just have a clock enabled~ never mind, finally found the culprit: a negative bottom margin. Waybar shows the tray just fine in River now. But Eww is so much more fun... stuck_out_tongue

Well looking at that line, it would seem to be a gtk issue

**Comment by dnordstrom** [comment]
Yeah, indeed. Maybe I'm missing some dependency, I don't know. I'm still running this branch, can try it in Sway when I get a chance and see if it works there. Wish I knew more Rust and could be more helpful.

EWW is awesome either way though, crazy addictive. For now, I'm just changing the settings so that apps don't close to tray. :slightly_smiling_face:

**Comment by dnordstrom** [comment]
Exactly the same stack trace in Sway as well.

**Comment by tralph3** [comment]
What's needed for this to be merged? No system tray is the only thing keeping me from using eww as my main bar.

**Comment by yavko** [comment]
> What's needed for this to be merged? No system tray is the only thing keeping me from using eww as my main bar.

This NEEDS to be merged, I know eww has slowed down in development, but for those of us who want the power of eww, this is kind of a deal breaker, what is a bar without a system tray. (a GNOME panel)

**Comment by sunziping2016** [comment]
I tried this PR and it seems to be a prototype with lots of problems. Currently, I am trying hard to implement a system tray based on the same idea. However, Linux's system tray specifications are really complicated.

**Comment by oknozor** [comment]
Hey @sunziping2016 I am currently working on something else but maybe we can join our effort ? 

This is indeed a prototype but it's not far form being usable. Actually I am using it as a daily driver.
If you want to help improving the current behavior maybe we can work together on https://github.com/oknozor/stray/ ? 

The main issue, imo is not the dbus system tray implementation, but the gtk integration, which require building a custom `MenuModel` and involve messing with some ffi bindings with the C api. 

If anyone has experience with gtk-rs help would be more than welcome.

**Comment by MonAaraj** [comment]
Awesome. I have been waiting for this feature for forever. If there's anything I can do (I *do* have Rust experience, just not `gtk-rs`) -- then let me know.

**Comment by kapilpokhrel** [comment]
Any updates on this?

**Comment by eclairevoyant** [comment]
> Any updates on this?

Bit inappropriate in open-source, especially when people are devoting their free time to unpaid work.
https://teejeetech.medium.com/etiquette-in-open-source-projects-f302b6e19c38
> Asking for ETAs — Avoid asking for ETAs for issues and feature requests. It’s more rude than you may realize. People working on open-source projects are not your employees. They have no obligation to implement every feature you request, to fix every issue you report, or to provide technical support that you are not even paying for. I do not enjoy spending my time working on features that are of no interest to me, or investigating issues that I never face. If I fix such an issue, it’s usually because I’m curious as to what’s causing it, or because that issue is affecting a lot of people and can be fixed quickly. The same goes for feature requests. I may add a feature for the sake of completeness, because it’s interesting, or maybe because it’s easy to implement. If it’s time consuming then it will remain undone till I find the time, or till someone else comes along, implements the feature, and submits a pull request.

**Comment by kapilpokhrel** [comment]
> > Any updates on this?
> 
> Bit inappropriate in open-source, especially when people are devoting their free time to unpaid work.
> Also irrelevant to the technical discussion of the PR itself.
> https://teejeetech.medium.com/etiquette-in-open-source-projects-f302b6e19c38
> > **Asking for ETAs** — Avoid asking for ETAs for issues and feature requests. It’s more rude than you may realize. People working on open-source projects are not your employees. They have no obligation to implement every feature you request, to fix every issue you report, or to provide technical support that you are not even paying for. I do not enjoy spending my time working on features that are of no interest to me, or investigating issues that I never face. If I fix such an issue, it’s usually because I’m curious as to what’s causing it, or because that issue is affecting a lot of people and can be fixed quickly. The same goes for feature requests. I may add a feature for the sake of completeness, because it’s interesting, or maybe because it’s easy to implement. If it’s time consuming then it will remain undone till I find the time, or till someone else comes along, implements the feature, and submits a pull request.
> 
> If you want to contribute, I imagine submitting your own PR would be far more welcome.

I am very sorry, I didn't realize that.
I was just very excited to see this PR. Again, sorry, I didn't want to be rude.

**Comment by yavko** [comment]
Also the pr author has started his own bar project, so i doubt he will complete this pr soon

**Comment by Anarky** [comment]
@oknozor I used your fork to try the systray integration, then added this on my `yuck` file:
```
(defwidget systray []
	(system-tray))
```

But the window is empty, and it prints in the log `thread 'tokio-runtime-worker' panicked at 'Error occurred in notifier watcher task: name already taken on the bus', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/stray-0.1.1/src/lib.rs:38:18`.
I'm using Awesome WM so I tried to remove its systray management but the problem is still there.

I also tried to rebase this PR, but when I try to compile with stray v0.1.0 or v0.1.2 the compilation raises those errors:
```
error[E0432]: unresolved imports `stray::tokio_stream`, `stray::SystemTray`
  --> crates/eww/src/widgets/system_tray.rs:14:5
   |
14 |     tokio_stream::StreamExt,
   |     ^^^^^^^^^^^^ could not find `tokio_stream` in `stray`
15 |     SystemTray,
   |     ^^^^^^^^^^ no `SystemTray` in the root

warning: unused import: `glib::signal::SignalHandlerId`
  --> crates/eww/src/widgets/widget_definitions.rs:14:5
   |
14 | use glib::signal::SignalHandlerId;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0308]: mismatched types
   --> crates/eww/src/widgets/system_tray.rs:109:53
    |
109 |                     state.insert(id, NotifierItem { item, menu });
    |                                                     ^^^^ expected struct `StatusNotifierItem`, found struct `Box`
    |
    = note: expected struct `StatusNotifierItem`
               found struct `std::boxed::Box<StatusNotifierItem>`
help: consider unboxing the value
    |
109 |                     state.insert(id, NotifierItem { item: *item, menu });
    |                                                     +++++++

warning: unused import: `std::hash::Hasher`
  --> crates/eww/src/widgets/widget_definitions.rs:18:5
   |
18 | use std::hash::Hasher;
   |     ^^^^^^^^

**Comment by VuiMuich** [comment]
This snippet – taken from the `gtk-tray` example on the `stray` repo (except the unbox in line 111) – works for me:
```diff, rust
diff --git a/crates/eww/src/widgets/system_tray.rs b/crates/eww/src/widgets/system_tray.rs
index bc2e088..c297e58 100644
--- a/crates/eww/src/widgets/system_tray.rs
+++ b/crates/eww/src/widgets/system_tray.rs
@@ -11,8 +11,7 @@ use stray::{
         tray::StatusNotifierItem,
         NotifierItemCommand, NotifierItemMessage,
     },
-    tokio_stream::StreamExt,
-    SystemTray,
+    StatusNotifierWatcher,
 };
 use tokio::{runtime::Runtime, sync::mpsc};

@@ -85,11 +84,14 @@ pub fn start_communication_thread(sender: mpsc::Sender<NotifierItemMessage>, cmd
         let runtime = Runtime::new().expect("Failed to create tokio RT");

         runtime.block_on(async {
-            let mut tray = SystemTray::new(cmd_rx).await;
+            let tray = StatusNotifierWatcher::new(cmd_rx).await.unwrap();
+            let mut host = tray.create_notifier_host("MyHost").await.unwrap();

-            while let Some(message) = tray.next().await {
+            while let Ok(message) = host.recv().await {
                 sender.send(message).await.expect("failed to send message to UI");
             }
+
+            host.destroy().await.unwrap();
         })
     });
 }
@@ -106,7 +108,7 @@ pub fn spawn_local_handler(

             match item {
                 NotifierItemMessage::Update { address: id, item, menu } => {
-                    state.insert(id, NotifierItem { item, menu });
+                    state.insert(id, NotifierItem { item: *item, menu });
                 }
                 NotifierItemMessage::Remove { address } => {
                     state.remove(&address);
```

**Comment by Anarky** [comment]
@VuiMuich thanks for your help! I attached a zip containing a patch that applies for the current revision ([678e4db](https://github.com/elkowar/eww/commit/678e4dbc6b6439bf50898ae2b13fcc65900c439c)) with stray 0.1.2, and a PKGBUILD for arch.
Unfortunately it still doesn't work for me, even when using `startx` I have this error:
```
thread 'tokio-runtime-worker' panicked at 'Unexpected StatusNotifierError : DbusError(NameTaken)', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/stray-0.1.2/src/notifier_watcher/mod.rs:37:22
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DbusError(NameTaken)', crates/eww/src/widgets/system_tray.rs:88:70
```

[stray.zip](https://github.com/elkowar/eww/files/10279788/stray.zip)

**Comment by VuiMuich** [comment]
It does not run very stable for me neither. I tried to put `stray` in a window to toggle it on and off, but that causes some panics as well. Had no time yet, to debug that.

**Comment by ralismark** [comment]
> For what it's worth, I'm trying this out on NixOS on River (Wayland) and I get the following error about icon info lookup:
> ```
> thread 'main' panicked at 'Failed to lookup icon info', crates/eww/src/widgets/system_tray.rs
> ```

@dnordstrom I had the same issue and did a bit of digging and I don't think it's an issue with this project. It seems to be https://github.com/NixOS/nixpkgs/issues/163107/. The fix at the bottom of this comment -- https://github.com/NixOS/nixpkgs/issues/163107#issuecomment-1100569484 -- worked for me.

**Comment by ralismark** [comment]
This is a feature I want, but the PR has kinda stalled, so I've been fixing some things over at https://github.com/ralismark/eww. I'm happy to try and get this into a mergeable state, but I haven't properly looked at all of the current changes, plus I'll be a bit busy for the next few weeks, so it might take some time.

@elkowar @oknozor what are your thoughts?

**Comment by PhilTaken** [comment]
@ralismark besides the fix for nixos, does your fork's systray work properly? I would be very interested in testing it

**Comment by tkapias** [comment]
I tried to use @ralismark's fork but after some groking only 1 of 6 icons appeared.

I hope that this features will get more attention, in the meantime I use [Stalonetray](https://github.com/kolbusa/stalonetray) with a eww button widget to toggle it.

**Comment by ralismark** [comment]
@tkapias 

> I tried to use @ralismark's fork but after some groking only 1 of 6 icons appeared.

I think this is because of a bug in https://github.com/oknozor/stray; i've made a workaround in my fork for now. I've also added the `:active-only` property -- set this to false (e.g. a `(system-tray :active-only false)` widget) to see all icons, not just ones that say they should be shown.

Can you have another go and see if the problem is still there?

**Comment by PhilTaken** [comment]
@ralismark 

> Can you have another go and see if the problem is still there?

I just tried it and it works for me :+1: 
Little heads-up, I could not get the latest commit to work with nix and had to refer to [68471c9b23e55ad3c8b31a99473552e16594a44f](https://github.com/ralismark/eww/tree/68471c9b23e55ad3c8b31a99473552e16594a44f).

**Comment by tkapias** [comment]
@ralismark

Thank you, there is some improvement but I have only the GTK icons.

- I killed eww daemon and added a basic widget for system-tray :
- I disabled Stalonetray and rebooted to be sure to free the bus.

```lisp
(defwidget tray []
    (system-tray :active-only false
                 :pack-direction "ltr"
    )
)
```

I should see 6 icons, but only the 3 GTK ones are displayed:

- Redshift-gtk: ok
- Solaar (gtk): icon not found; I see a default picture
- xpad: ok

QT ones are not:

- KeepassXC (qt)
- nm-tray (qt)
- qtalarm (qt)

Strangely, in my mind, the last time I remember that I had only qtalarm displayed (qt), but I may be wrong.

**Comment by ItsDrike** [comment]
@ralismark 

For me, the discord icon is sometimes shown incorrectly, see image below:
image

I'm not sure what causes this to happen, as it doesn't always happen, and in many cases, the discord icon is shown properly for quite a long time (hours), but eventually, it just turns into that weird icon on the image above. Closing and reopening discord fixes this
image

Also, as a sidenote, I'd perhaps suggest to enable issues on your fork repo, so that people wouldn't have to report the issues with it on this PR, and you could track individual issues in their own threads. Alternatively, you could just open another PR from your fork instead. It's kind of weird to solve all of these issues here.

**Comment by ralismark** [comment]
I've opened a new PR for my continuation of this:
- #676

**Comment by rsammelson** [comment]
I've been trying this out, but I am having an issue where when I right click on various apps in the tray and click quit, the apps do not quit (I don't think any app I have tried quits properly). Any tips to fix this?

**Comment by 0xC0ncord** [comment]
Is there anything left to do here now that https://github.com/elkowar/eww/pull/743 is merged?

**Comment by dacyberduck** [comment]
> I've been trying this out, but I am having an issue where when I right click on various apps in the tray and click quit, the apps do not quit (I don't think any app I have tried quits properly). Any tips to fix this?

I have had the same issue. I installed waybar to check if the issue was eww related or something else. However aster installing waybar the issue is resolved. I am assuming it requires some dependency that is not mentioned in the documentation. Not sure but maybe the libayatana-appindicator library. 🤷

**Comment by ralismark** [comment]
> Is there anything left to do here now that #743 is merged?

That PR completely supersedes this one. This PR can be closed.

**Comment by elkowar** [comment]
Closing! I'm unbelievably thankful for everyone involved in making systrays happen, this has been one of the most important features in recent EWW development. Thank you all so, so much! <3
