### PR TITLE
feat: update to 1.80.1 toolchain; dependency updates

### LINKED ISSUE #808: [BUG] some scss functions no longer work
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

After updating eww to the latest commit (coming from the release branch) I noticed it no longer recognized common scss functions (notably `string.unique-id()` and possibly others I haven't checked).
After some digging I found that removing the `default-features` flag from grass in `Cargo.toml` fixes this issue

Seems like this change was made for [faster build times](https://github.com/elkowar/eww/commit/7a0e1b77f24ee89d627e552f9abc55eb636aaaa6) and should have no noticeable impact however I lack much knowledge of rust and this project so unsure if it has any unintended issues.

### Reproducing the issue

use the following scss code
```scss
@use "sass:string";

$unique: string.unique-id();
```
and it will not execute the function

### Expected behaviour

it should've ran the function as expected

### Additional context

_No response_

### LINKED ISSUE #1141: [BUG] Unable to install eww with yay -S eww
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When I try to install eww with 

`yay -S eww `

I got compilation errors. See screenshot below. Not able to install eww.

### Reproducing the issue

Install eww on Arch based distros with

`yay -S eww`

### Expected behaviour

eww should be installed correctly with

`yay -S eww`

### Additional context

image

### LINKED ISSUE #1156: [BUG] master fails to build on rust-1.80.1
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Using locally build rust-1.80.1
[gui-apps:eww-9999:20240814-220722.log.gz](https://github.com/user-attachments/files/16619557/gui-apps.eww-9999.20240814-220722.log.gz)
Currently testing from binary package.

### Reproducing the issue

_No response_

### Expected behaviour

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by w-lfchen**
## Description
**specific details on some crate updates can be found below**
motivated by and closes #1141
closes #1156 
motivated by NixOS/nixpkgs#332957 (eww is currently building in nixpkgs through a lockfile patch)
supersedes #1137 (patch has been applied in a004136779fb0dd0a710d7947158f928e7a8a140)
supersedes #809 (see below), therefore also closes #808
basic functionality tested (systray not tested, my config does not contain one)
reduces build times by dropping ~40 crates in the dependency tree

- update rust toolchain to 1.80.1
- update flake.lock
- update almost all dependencies, 4 have been left out, see below
- switch to nixfmt-rfc-style for nix formatting
- fix new lints
note: there are warnings about unused struct fields now, this probably should be addressed

## `dbusmenu-glib` breaks when automatically updating the missing dependencies
i don't know enough about this to even attempt to fix it, but i'd love to integrate a fix before opening this pr.
### after 4cf9d2d7e460af8f0ff5fcc5378615be95d3ed0e
running `cargo update --dry-run` yields the following:
```
    Updating crates.io index
     Locking 6 packages to latest compatible versions
      Adding gdk-pixbuf-sys v0.20.0
      Adding gio-sys v0.20.0
      Adding glib v0.20.0
      Adding glib-macros v0.20.0
      Adding glib-sys v0.20.0
      Adding gobject-sys v0.20.0
note: pass `--verbose` to see 63 unchanged dependencies behind latest
warning: not updating lockfile due to dry run
```
When adding these crates by simply running `cargo update`, `dbusmenu-glib` fails to compile:
```
error[E0433]: failed to resolve: could not find `ObjectExt` in `glib`
   --> <home>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbusmenu-glib-0.1.0/src/auto/client.rs:203:15
    |
203 |         glib::ObjectExt::property(self.as_ref(), "dbus-name")
    |               ^^^^^^^^^ could not find `ObjectExt` in `glib`
    |
help: a struct with a similar name exists
    |
203 |         glib::Object::property(self.as_ref(), "dbus-name")
    |               ~~~~~~
help: consider importing this trait
    |
6   + use glib::prelude::ObjectExt;
    |
help: if you import `ObjectExt`, refer to it directly
    |
203 -         glib::ObjectExt::property(self.as_ref(), "dbus-name")
203 +         ObjectExt::property(self.as_ref(), "dbus-name")
    |
```
there are multiple errors like this one, since the [`dbusmenu-gtk3`](https://github.com/ralismark/dbusmenu-rs) crate and a few others that seem to be linked to it are auto-generated, something probably needs to be adjusted in the generation process.

### before 4cf9d2d7e460af8f0ff5fcc5378615be95d3ed0e
running `cargo update --dry-run` yields the following:
```
     Locking 4 packages to latest compatible versions
      Adding gdk-pixbuf-sys v0.20.0
      Adding gio-sys v0.20.0
      Adding glib-sys v0.20.0
      Adding gobject-sys v0.20.0
note: pass `--verbose` to see 90 unchanged dependencies behind latest
warning: not updating lockfile due to dry run
```
note that everything seems to work without them and that `gdk-pixbuf-sys` seems to depend on the other 3.
When adding these crates, `dbusmenu-glib` fails to compile:
```
    |
586 |             FromGlibPtrContainer::from_glib_none(ffi::dbusmenu_menuitem_get_children(self.as_ref().to_glib_none().0))
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `glib::translate::FromGlibPtrArrayContainerAsVec<_, *mut glib_sys::GList>` is not implemented for `menuitem::Menuitem`, which is required by `Vec<menuitem::Menuitem>: glib::translate::FromGlibPtrContainer<_, *mut glib_sys::GList>`
    |
    = help: the following other types implement trait `glib::translate::FromGlibPtrArrayContainerAsVec<P, PP>`:
              <menuitem::Menuitem as glib::translate::FromGlibPtrArrayContainerAsVec<*mut DbusmenuMenuitem, *const *mut DbusmenuMenuitem>>
              <menuitem::Menuitem as glib::translate::FromGlibPtrArrayContainerAsVec<*mut DbusmenuMenuitem, *mut *mut DbusmenuMenuitem>>
    = note: required for `Vec<menuitem::Menuitem>` to implement `glib::translate::FromGlibPtrContainer<_, *mut glib_sys::GList>`

```
there are multiple errors like this one.

## re-enable grass default features
80a5a453c71f697f23822b2aa59945ccf126c803 re-enabled default features.
running `cargo clean && cargo build` produced the exact same compilation times for me, so the argument brought up in #606 no longer holds.

## derive_more v1.0.0
the most notable breaking change is that now, all features should be enabled manually, which i've done.

## Checklist

- [x] I added my changes to CHANGELOG.md, if appropriate.
- [x] I used `cargo fmt` to automatically format all code before committing
- [x] I used `nix fmt` to automatically format all code before committing

### CODE REVIEW

File: crates/yuck/src/parser/ast_iterator.rs [hunk 1]
```diff
@@ -90,7 +90,7 @@ impl<I: Iterator<Item = Ast>> AstIterator<I> {
         parse_key_values(self, true)
     }
 
-    pub fn put_back(&mut self, ast: Ast) {
+    pub fn put_back(&mut self, ast: Ast) -> Option<Ast> {
```
Comment (w-lfchen) [inline crates/yuck/src/parser/ast_iterator.rs:93]: API change for more flexibility, doesn't cause issues

**Comment by w-lfchen** [comment]
everything should be up to date at the time of writing this

**Comment by elkowar** [comment]
Thank you so much for your work!
